// <auto-generated />
using System;
using AltIEn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltIEn.Migrations
{
    [DbContext(typeof(RetContext))]
    [Migration("20230116153156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("AltIEn.Model.Ingrediens", b =>
                {
                    b.Property<int>("IngrediensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngrediensId");

                    b.HasIndex("RetId");

                    b.ToTable("Ingredienser");
                });

            modelBuilder.Entity("AltIEn.Model.Ret", b =>
                {
                    b.Property<int>("RetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RetId");

                    b.ToTable("Retter");
                });

            modelBuilder.Entity("AltIEn.Model.Ingrediens", b =>
                {
                    b.HasOne("AltIEn.Model.Ret", null)
                        .WithMany("Ingredienser")
                        .HasForeignKey("RetId");
                });

            modelBuilder.Entity("AltIEn.Model.Ret", b =>
                {
                    b.Navigation("Ingredienser");
                });
#pragma warning restore 612, 618
        }
    }
}
